language: node_js
node_js:
    - 8
os:
    - linux
branches:
    only:
    - master
install:
    - npm install
stages:
    - test
    - name: deploy
jobs:
  include:
    - stage: test
     script:
       - node --version
       - npm --version
       - echo "Testing Started ..."
       - echo "Testing Finished."

    - stage: deploy
     script:
       - echo "NPM Deploying Started ..."
       - npm version
       - npm run prepare
       - echo "NPM Building Finished."

     deploy:
       provider: npm
       email: "$NPM_Email"
       api_key: "$NPM_TOKEN"
       skip_cleanup: true
       on:
         all_branches: true

